# Site
name: 'LSE Law Review Blog'
description: 'A student-run law journal seeking to provide a platform for high quality legal scholarship.'
logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: '/'
disqus: 'lse-law-review'
email: 'lselawreview@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

## Find Old References:
# \[([^\[]+)\] (.+\n)*
## Replace with:
# <a class="reference" id="$1" href="#inline$1">[$1]</a>\n$2

## Find Old Inline References
# \[([^\[]+)\]
## Replace with:
# <a class="inline-reference" id="inline$1" href="#$1">$1</a>

include: ["_pages"]
permalink: /:year/:month/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authorcategories:
    editor:
      name: "Notes Editors"
    contributor:
      name: "Contributors"

authors:

    austin:
      name:           "Austin Chan"
      avatar:         /assets/images/austinchan.jpg
      bio:            "LLB (London School of Economics and Political Science) '20 and Management Editor of the LSE Law Review 2018-2019"
      email:          h.chan21@lse.ac.uk
      category:       contributor

    claudia:
      name:           "Claudia Tam"
      bio:            "LLB (University of Hong Kong) '19"
      category:       contributor

    ching:
      name:           "Ching Suen"
      bio:            "LLB (London School of Economics and Political Science) '21 and Private Notes Editor of the LSE Law Review Summer Board 2019"
      category:       editor

    floris:
      name:           "Dr. Floris de Witte"
      bio:            "Assistant Professor of Law at the London School of Economics and Political Science"
      email:          f.e.de-witte@lse.ac.uk
      category:       contributor

    gloria:
      name:           "Gloria Schiavo"
      avatar:         /assets/images/gloriaschiavo.jpg
      bio:            "LLB (London School of Economics and Political Science) '20 and Editor-in-Chief of the LSE Law Review 2019-2020"
      email:          g.schiavo@lse.ac.uk
      category:       contributor

    isabel:
      name:           "Isabel Hahn"
      avatar:         /assets/images/isabelhahn.jpg
      bio:            "LLB (London School of Economics and Political Science) '20 and Articles Editor of the LSE Law Review Summer Board 2018"
      email:          i.hahn@lse.ac.uk
      category:       contributor

    jason:
      name:           "Jason Lin"
      bio:            "LLB (London School of Economics and Political Science) '21 and Criminal Law Notes Editor of the LSE Law Review Summer Board 2019"
      category:       editor


    josias:
      name:           "Josias Senu"
      bio:            "LLB (London School of Economics and Political Science) '19 and Articles Editor of the LSE Law Review Summer Board 2018"
      email:          josiah_senu@yahoo.com
      category:       contributor

    jonathan:
      name:           "Jonathan Fisher QC"
      bio:            "Visiting Professor in Practice at the London School of Economics and Political Science"
      email:          j.s.fisher@lse.ac.uk
      category:       contributor

    lora:
      name:           "Lora Izvorova"
      avatar:         /assets/images/loraizvorova.jpg
      bio:            "LLM (University of Cambridge) '19 and Management Editor at the LSE Law Review 2017-2018"
      email:          lora.izvorova@gmail.com
      category:       contributor

    mahmoud:
      name:           "Mahmoud Serewel"
      bio:            "LLB (London School of Economics and Political Science) '19 and International Law Notes Editor of the LSE Law Review 2018-2019"
      email:          m.s.serewel@lse.ac.uk
      category:       contributor

    narjis:
      name:           "Narjis Khan"
      bio:            "LLM (Public International Law) (London School of Economics and Political Science) ‘16"
      category:       contributor

    thomas:
      name:           "Thomas Yeon"
      avatar:         /assets/images/thomasyeon.jpg
      bio:            "PCLL Candidate (HKU)'2020 and Public Law Notes Editor of the LSE Law Review Summer Board 2019"
      email:          yeonky1997@gmail.com
      category:       editor

    samantha:
      name:           "Samantha Goh"
      bio:            "LLM (International Law) (London School of Economics and Political Science) ‘21 and International Law Notes Editor of LSE Law Review Summer Board 2019"
      category:       editor

    simon:
      name:           "Simon Witney"
      bio:            "PhD Candidate at the London School of Economics and Political Science"
      email:          s.r.witney@lse.ac.uk
      category:       contributor

    william:
      name:           "William Wong"
      avatar:         /assets/images/williamwong.jpg
      bio:            "LLB (London School of Economics and Political Science) '20 and Private Law Notes Editor of the LSE Law Review 2018-2019"
      email:          williamwuilong@gmail.com
      category:       contributor

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
