# Site
name: 'LSE Law Review Blog'
description: 'A student-run law journal seeking to provide a platform for high quality legal scholarship.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
disqus: 'demowebsite'
email: 'lselawreview@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

## Find Old References:
# \[([^\[]+)\] (.+\n)*

## Replace with:
# <div class="reference" id="$1">[$1]: $2</div>\n


include: ["_pages"]
permalink: /:year/:month/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    gloria:
      name:           "Gloria Schiavo"
      avatar:         /assets/images/avatar1.jpg
      bio:            "I am a very annoying sister!"
      email:          g.schiavo@lse.ac.uk

    thomas:
      name:           Thomas Yeon
      avatar:         /assets/images/avatar2.jpg
      bio:            "LLM (Human Rights Law) (LSE) ‘19"
      email:          fakemail@gmail.com

    claudia:
      name:           Claudia Tam
      avatar:         /assets/images/avatar3.jpg
      bio:            "LLB (HKU) ‘19"
      email:          tcook@apple.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
