# Site
name: 'LSE Law Review Blog'
description: 'A student-run law journal seeking to provide a platform for high quality legal scholarship.'
logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: '/'
disqus: 'lse-law-review'
email: 'lselawreview@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

## Find Old References:
# \[([^\[]+)\] (.+\n)*

## Replace with:
# <div class="reference" id="$1">[$1]: $2</div>\n


include: ["_pages"]
permalink: /:year/:month/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:

    claudia:
      name:           "Claudia Tam"
      bio:            "LLB (University of Hong Kong) '19"

    floris:
      name:           "Floris de Witte"
      bio:            "Assistant Professor of Law at the London School of Economics and Political Science"
      email:          f.e.de-witte@lse.ac.uk      

    gloria:
      name:           "Gloria Schiavo"
      avatar:         /assets/images/gloriaschiavo.jpg
      bio:            "LLB (London School of Economics and Political Science) '20 and Editor-in-Chief of the LSE Law Review 2019-2020"
      email:          g.schiavo@lse.ac.uk

    thomas:
      name:           "Thomas Yeon"
      avatar:         /assets/images/thomasyeon.jpg
      bio:            "LLM (Human Rights Law) (London School of Economics and Political Science) ‘19 and Public Law Notes Editor of LSE Law Review 2018-2019"
      email:          k.y.yeon@lse.ac.uk

    narjis:
      name:           "Narjis Khan"
      bio:            "LLM (Public International Law) (London School of Economics and Political Science) ‘16"

    simon:
      name:           "Simon Witney"
      bio:            "PhD Candidate at the London School of Economics and Political Science"
      email:          s.r.witney@lse.ac.uk
      


      
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
